#include "myy/helpers/temp_string.h"

#include <stdarg.h>

char * temp_string_text_set(
	temp_string_t * __restrict const temp_string,
	char const * __restrict const text)
{
	myy_vector_utf8_reset(&temp_string->vector);	
	myy_vector_utf8_add(&temp_string->vector,
		strlen(text),
		(uint8_t const *) text);
	return temp_string_text(temp_string);
}

char * temp_string_text_set_format(
	temp_string_t * __restrict const temp_string,
	char const * __restrict const fmt,
	...)
{
	myy_vector_utf8 * __restrict const ts_vector =
		&temp_string->vector;
	va_list fmt_list;
	va_start(fmt_list, fmt);
	int const required_size =
		vsnprintf((char *) 0, 0, fmt, fmt_list)
		+ sizeof('\0');
	myy_vector_utf8_ensure_enough_space_for(
		ts_vector, required_size);

	/* Take the minimum size between what's allocated for
	 * the string vector and the required_size.
	 * Be sure that we can put a '\0' at the end of the
	 * string generated by vsnprintf.
	 */
	size_t const vector_total_size =
		myy_vector_utf8_allocated_total(ts_vector)
		- sizeof('\0');
	size_t const final_string_size =
		vector_total_size > required_size
		? required_size
		: vector_total_size;
	char * __restrict const text = temp_string_text(temp_string);
	vsnprintf(
		temp_string_text(temp_string),
		final_string_size,
		fmt,
		fmt_list);
	text[final_string_size-1] = '\0';
	myy_vector_utf8_force_length_to(ts_vector, final_string_size);
	return temp_string_text(temp_string);
}
